### PR TITLE
Giant pull request

### PR DESCRIPTION
**Pull request by haleystorm**
Too many changes to be reviewed but maybe we can start a dialog on merging.

### CODE REVIEW

**Comment by kengu** [comment]
Hi!

I haven't look through all yet, but I like what I've seen done so far. I'm probably going to accept this pull-request. Travis build passes and it can be merged without any conflicts. Good job! Since it's a big merge, I'll have to do some additional QA on it before I merge it into master.

**Comment by kengu** [comment]
@haleystorm: I've finished QA. Accept from some minor coding-style differences between existing and new code, all looks really good. So I can happily merge this pull-request. Your effort is much apprecieted. Thanks!

**Comment by haleystorm** [comment]
Oh and thanks for accepting my pull request! This is my first contribution to an open source project. So excited.

**Comment by kengu** [comment]
@haleystorm: Yes, I hit the same problem when looking into why the unit test suddenly broke. Travis did no report the error because a configuration error which skipped all tests by default. After fixing that, unit tests broke in a way indicating that the leaflet.js was not loaded any more. 

**Cause**: I found out after some digging that you had changed the external library inclusion strategy to solve the problem with Cross-Site-Iframe linker no longer accepting script-tags in module files (default enabled in GWT 2.7.0 in dev mode). Since external libraries after the change requires all external libraries to be manually added in html, unit tests in gwtl-core, which depends on htmlunit, broke because htmlunit is headless (no html) and can therefore not know about the dependency on leaflet.js. 

**Resolution**: I've kept your strategy with one slight change. Instead of adding external resources to the default folder `public` (in the resource folder), I added all external libraries into a new folder called `client` instead (rename). which allows me to implement a ClientBundle which injects external javascript which unit tests depends into the module only when testing. Note that all public resources are still copied to `libs` folder in all maven artifacts as before. 

**Important**: 
1. You'll need to merge/rebase these changes back into your fork. As a bonus, this will also enable unit testing again, which will prevent the same type error occurring again.
2. We need to document the new external library inclusion strategy, since all existing uses of gwt-leaflet will break until script and stylesheet tags are added manually.

**Comment by kengu** [comment]
I'll keep looking into solutions which allow users to inject libraries automatically without any need for manual inclusion of script and stylesheet tags in html .

**Comment by kengu** [comment]
I think your solution is probably the only way forward. If we keep the old strategy and just add <set-`configuration-property name='xsiframe.failIfScriptTag' value='FALSE'/>`, this will probably keep getting us into trouble later on (found several advocates for this view googling the problem) as super dev mode becomes the default way of working. Do you have any take on this?

**Comment by haleystorm** [comment]
Sounds good to me. I haven't been using super dev mode but many projects do. I can add the new external library inclusion strategy to the README.

**Pull request merged**
